<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Projet;
use AppBundle\Form\ProjetEditType;
use AppBundle\Form\ProjetType;
use http\Env\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProjetController extends Controller
{
    /**
     * @Route("/backend/newProjet", name="new_projet")
     */
    public function newProjetAction(Request $request)
    {
        $projet = new Projet();
        $projet->setUser($this->getUser());
        $form = $this->createForm(ProjetType::class, $projet);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['attachment']->getData();

            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            // Move the file to the directory where brochures are stored
            try {
                $file->move("/opt/www/portfolio/web/images",
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
                dump($e);
            }

            $projet->setImageProjet($fileName);

            $shortDescription = substr($projet->getDescriptionProjet(), 0, 251);


            if (strlen($shortDescription) == 251 ) {
                $projet->setShortDescriptionProjet($shortDescription." ...");
            }
            else {
                $projet->setShortDescriptionProjet($shortDescription) ;
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($projet);
            $em->flush();

            return $this->redirectToRoute('liste_projet');

        }


        return $this->render('projet/newProjet.html.twig', array(
            'form' => $form->createView(),
        ));
    }


    /**
     * @Route("/backend/listeProjet", name="liste_projet")
     */
    public function listeProjetAction()
    {
        $listeProjet = $this->getDoctrine()->getRepository('AppBundle:Projet')->findBy(array("user" => $this->getUser()));
        return $this->render('projet/listeProjet.html.twig', array(
            'listeProjet' => $listeProjet,
        ));
    }

    /**
     * @Route("backend/projet/view/{id}", name="view_projet")
     */
    public function viewProjetAction(Projet $projet)
    {
        return $this->render('projet/viewProjet.html.twig', array(
            'projet'    => $projet,
        ));
    }

    /**
     * @Route("/backend/remove/{projet}", name="remove_projet")
     */
    public function removeProjetAction(Projet $projet)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($projet);
        $em->flush();

        return $this->redirectToRoute('liste_projet');
    }

    /**
     * @Route("/backend/edit/projet/{projet}", name="edit_projet")
     */
    public function editProjetAction(Projet $projet, Request $request)
    {
        $formEdit = $this->createForm(ProjetEditType::class, $projet);
        $formEdit->handleRequest($request);

        if ($formEdit->isValid() && $formEdit->isSubmitted())
        {
            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirectToRoute('liste_projet');
        }

        return $this->render('projet/editProjet.html.twig', array(
            'form'  => $formEdit->createView(),
        ));


    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
